/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hmjZPVicNZ7
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { ResponsiveBar } from "@nivo/bar"

export function Class() {
  return (
    <div className="bg-white p-8">
      <div className="border-b border-red-800 pb-4">
        <h1 className="text-4xl font-bold text-gray-900">Mathematical Machine Learning</h1>
        <p className="text-xl text-gray-600">COMP SCI 761</p>
      </div>
      <div className="">
        <div className="my-4">
          <label className="block text-sm font-medium text-gray-700" htmlFor="instructors">
            Instructors
          </label>
          <Select>
            <SelectTrigger id="instructors">
              <SelectValue placeholder="All Instructors" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="instructor1">Instructor 1</SelectItem>
              <SelectItem value="instructor2">Instructor 2</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700" htmlFor="semesters">
            Semesters
          </label>
          <Select>
            <SelectTrigger id="semesters">
              <SelectValue placeholder="All Semesters" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="semester1">Semester 1</SelectItem>
              <SelectItem value="semester2">Semester 2</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="mt-6 flex flex-col gap-4">
        <div className="col-span-2">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Mathematical Machine Learning: Cumulative</h2>
          <BarChart className="w-full h-[300px]" />
        </div>
        <div className="grid grid-flow-col gap-4">
          <div className="bg-red-100 p-4 rounded-lg">
            <h3 className="text-lg font-semibold text-gray-900">Total Entries</h3>
            <p className="text-3xl font-bold text-red-800">417</p>
          </div>
          <div className="bg-red-100 p-4 rounded-lg">
            <h3 className="text-lg font-semibold text-gray-900">Average GPA</h3>
            <p className="text-3xl font-bold text-red-800">3.645</p>
          </div>
          <div className="bg-red-100 p-4 rounded-lg">
            <h3 className="text-lg font-semibold text-gray-900">Percentage A</h3>
            <p className="text-3xl font-bold text-red-800">51.08%</p>
          </div>
        </div>
      </div>
    </div>
  )
}


function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function BarChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "A", count: 55 },
          { name: "AB", count: 25 },
          { name: "B", count: 10 },
          { name: "BC", count: 5 },
          { name: "C", count: 3 },
          { name: "D", count: 1 },
          { name: "F", count: 1 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#840024"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }: any) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  )
}
