/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hmjZPVicNZ7
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { ResponsiveBar } from "@nivo/bar"
import { HoverEffect } from "../ui/card-hover-effect"

export function Instructor() {
    return (
        <div className="bg-white">
            <div className="p-8">
                <div className="border-b border-red-800 pb-4">
                    <h1 className="text-4xl font-bold text-gray-900">KRISTIN PHILLIPS-COURT</h1>
                    <p className="text-xl text-gray-600">Instructor</p>
                </div>
                <div className="mt-6 flex flex-col gap-4">
                    <div className="col-span-2">
                        <h2 className="text-lg font-semibold text-gray-900 mb-4">Overall Grades Given</h2>
                        <BarChart className="w-full h-[300px]" />
                    </div>
                    <div className="grid grid-cols-3 border-b border-red-800 pb-4 gap-4">
                        {/* <div className="bg-red-100 p-4 rounded-lg">
                            <h3 className="text-lg font-semibold text-gray-900">Rate My Professor</h3>
                            <p className="text-3xl font-bold text-red-800">4.5/5</p>
                        </div>
                        <div className="bg-red-100 p-4 rounded-lg">
                            <h3 className="text-lg font-semibold text-gray-900">Difficulty</h3>
                            <p className="text-3xl font-bold text-red-800">2/5</p>
                        </div> */}
                        <div className="bg-red-100 p-4 rounded-lg">
                            <h3 className="text-lg font-semibold text-gray-900">Students taught</h3>
                            <p className="text-3xl font-bold text-red-800">417</p>
                        </div>
                        <div className="bg-red-100 p-4 rounded-lg">
                            <h3 className="text-lg font-semibold text-gray-900">Average GPA</h3>
                            <p className="text-3xl font-bold text-red-800">3.645</p>
                        </div>
                        <div className="bg-red-100 p-4 rounded-lg">
                            <h3 className="text-lg font-semibold text-gray-900">Percentage A</h3>
                            <p className="text-3xl font-bold text-red-800">51.08%</p>
                        </div>
                    </div>
                </div>

            </div>
            <div className="px-6">
                <h3 className="text-2xl font-semibold text-gray-900 px-2">Classes Taught</h3>
                <HoverEffect items={classes} />
            </div>
        </div>
    )
}

export const classes = [
    {
        title: "Mathematical Machine Learning",
        description:
            "COMP SCI 761",
        link: "https://stripe.com",
    },
    {
        title: "Mathematical Machine Learning",
        description:
            "COMP SCI 761",
        link: "https://stripe.com",
    }, {
        title: "Mathematical Machine Learning",
        description:
            "COMP SCI 761",
        link: "https://stripe.com",
    }, {
        title: "Mathematical Machine Learning",
        description:
            "COMP SCI 761",
        link: "https://stripe.com",
    },
    {
        title: "Mathematical Machine Learning",
        description:
            "COMP SCI 761",
        link: "https://stripe.com",
    },
    {
        title: "Mathematical Machine Learning",
        description:
            "COMP SCI 761",
        link: "https://stripe.com",
    },
];



function StarIcon(props: any) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
        </svg>
    )
}


function BarChart(props: any) {
    return (
        <div {...props}>
            <ResponsiveBar
                data={[
                    { name: "A", count: 111 },
                    { name: "AB", count: 157 },
                    { name: "B", count: 129 },
                    { name: "BC", count: 150 },
                    { name: "C", count: 119 },
                    { name: "D", count: 72 },
                    { name: "F", count: 72 },
                ]}
                keys={["count"]}
                indexBy="name"
                margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
                padding={0.3}
                colors={["#840024"]}
                axisBottom={{
                    tickSize: 0,
                    tickPadding: 16,
                }}
                axisLeft={{
                    tickSize: 0,
                    tickValues: 4,
                    tickPadding: 16,
                }}
                gridYValues={4}
                theme={{
                    tooltip: {
                        chip: {
                            borderRadius: "9999px",
                        },
                        container: {
                            fontSize: "12px",
                            textTransform: "capitalize",
                            borderRadius: "6px",
                        },
                    },
                    grid: {
                        line: {
                            stroke: "#f3f4f6",
                        },
                    },
                }}
                tooltipLabel={({ id }: any) => `${id}`}
                enableLabel={false}
                role="application"
                ariaLabel="A bar chart showing data"
            />
        </div>
    )
}
